version: '3.8'

services:
  postgres:
    image: postgres:15
    container_name: sigep_postgres
    restart: always
    environment:
      POSTGRES_USER: postgres
      POSTGRES_PASSWORD: postgres
      POSTGRES_DB: sigep
    ports:
      - "5432:5432"
    volumes:
      - pgdata:/data/postgres

volumes:
  pgdata: